### ISSUE TITLE
JavaScript injection

### ISSUE THREAD

**Issue by evg1n** [RD17/react-trumbowyg#22]
Hello,

I get the data inside Trumbowyg using this method. 

```
export default class TextEditor extends React.Component {
  constructor(props) {
    super(props);
    this.state={
      data : ""
    }
  }

  getData(event){
  // TODO: sanitize HTML
    this.setState({data: event.target.innerHTML})
  }

  render(){

    return(
      <Form>
        <Form.Field required={true}>
          <label>This field is required</label>
         <Trumbowyg onBlur={this.getData.bind(this)} id="react-trumbowyg"/>
        </Form.Field>
      </Form>
    )
  }
}
```

But I noticed, you can inject `<script>console.log("Hello World!")</script>` and it actually works on the client. I was even able to actually call a method from my server.

Isn't this a security issue? I think there must be a HTML sanitizer prop for this module. I will sanitize it myself.

It's still an awesome module. Thanks in advance.

**Comment by Alex-D** [comment]
Hey! I'm the Trumbowyg's creator and maintainer.

Since you are on the client-side, it's not a security issue: the user can do the same from Devtools Console. It becomes a security issue if you do not sanitize the HTML on the server-side before save it in your database. 

Client-side sanitization is useless. Someone can "disable" your sanitizer by posting the form content directly on your server... so you should do that on the server-side.

**Comment by evg1n** [comment]
Hello Alex-D,

Thank you for your response. For starters, I disabled the Raw HTML button. Then I defined a function on the server to sanitize Trumboywg data that client sent.

Cheers.
